builders:
  service_builder:
    import: "package:dartrofit_generator/builder.dart"
    builder_factories: [ "serviceBuilder" ]
    build_extensions: { ".dart": [ "service.g.part" ] }
    auto_apply: dependents
    build_to: cache
    applies_builders: [ "source_gen|combining_builder" ]
