name: dartrofit_generator
description: The source generator for dartrofit
version: 1.0.0
homepage: https://github.com/nikeorever/dartrofit/tree/master/dartrofit_generator

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  dartrofit: ^1.0.0
  build: ^1.3.0
  source_gen: ^0.9.6
  code_builder: ^3.4.1
  analyzer: ^0.39.14
  built_collection: ^4.3.2
  built_value: ^7.1.0
  quiver: ^2.1.3
  dart_style: ^1.3.6
  wedzera: ^0.1.0

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.3
  built_value_generator: ^7.1.0
  build_runner: ^1.10.1
  build_verify: ^1.1.1
