name: example
description: example of dartrofit.

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  dartrofit:
    path: ../dartrofit
  dartrofit_adapter_rx:
    path: ../dartrofit_adapters/adapter_rx
  dartrofit_converter_xml:
    path: ../dartrofit_converters/converter_xml

  logging: ^0.11.4
  mockserver:
    path: ../mockserver

  quiver: ^2.1.3
  wedzera: ^1.0.0



dev_dependencies:
  build_runner: ^1.10.1
  build_verify: ^1.1.1
  dartrofit_generator:
    path: ../dartrofit_generator

  pedantic: ^1.9.2
  test: ^1.15.3
