name: dartrofit_converter_json
description: The Json support for dartrofit.
version: 1.0.0
homepage: https://github.com/nikeorever/dartrofit/tree/master/dartrofit_converters/converter_json

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  dartrofit: ^1.0.0
  http_parser: ^3.1.4

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.3
  build_runner: ^1.10.1
  build_verify: ^1.1.1
  dartrofit_generator:
    path: ../../dartrofit_generator

  http_server: ^0.9.8+3
  mockserver:
    path: ../../mockserver
