name: dartrofit_converter_xml
description: The Xml support for dartrofit.
version: 1.0.0
homepage: https://github.com/nikeorever/dartrofit/tree/master/dartrofit_converters/converter_xml

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  dartrofit:
    path: ../../dartrofit
  http_parser: ^3.1.4
  xml: ^4.4.1

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.3
  build_runner: ^1.10.1
  build_verify: ^1.1.1
  dartrofit_generator:
    path: ../../dartrofit_generator

  http_server: ^0.9.8+3
  mockserver:
    path: ../../mockserver
