name: dartrofit_converter_xml
description: A Converter which uses xml for XML serialization.
version: 1.1.0
homepage: https://github.com/nikeorever/dartrofit/tree/trunk/dartrofit_converters/converter_xml

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  dartrofit:
    path: ../../dartrofit
  http_parser: ^3.1.4
  xml: ^4.5.1

dev_dependencies:
  build_runner: ^1.10.1
  build_verify: ^1.1.1
  dartrofit_generator:
    path: ../../dartrofit_generator

  mockserver:
    path: ../../mockserver

  pedantic: ^1.9.2
  test: ^1.15.3
