name: mockserver
description: Mock server base on http_server.
version: 0.0.1
homepage: https://github.com/nikeorever/dartrofit/tree/trunk/mockserver

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  http_server: ^0.9.8+3
  quiver: ^2.1.3
  wedzera: ^1.0.0

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.3
