name: samples
description: samples of dartrofit.

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  dartrofit:
    path: ../dartrofit
  dartrofit_adapter_rx:
    path: ../dartrofit_adapters/adapter_rx
  dartrofit_converter_xml:
    path: ../dartrofit_converters/converter_xml
  dartrofit_converter_json:
    path: ../dartrofit_converters/converter_json

  mockserver:
    path: ../mockserver

  logging: ^0.11.4

dev_dependencies:
  dartrofit_generator:
    path: ../dartrofit_generator

  pedantic: ^1.9.2
  test: ^1.15.3
  build_runner: ^1.10.1
  build_verify: ^1.1.1
