name: dartrofit_adapter_rx
description: The Rx support for dartrofit
version: 1.0.0
homepage: https://github.com/nikeorever/dartrofit/tree/master/dartrofit_adapters/adapter_rx

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  dartrofit: ^1.0.0
  rxdart: ^0.24.1
  wedzera: ^0.1.0

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.3
  build_runner: ^1.10.1
  build_verify: ^1.1.1
  dartrofit_generator: ^1.0.0

  mockserver:
    path: ../../mockserver
