name: dartrofit
description: A Retrofit-Like http client for Dart and Flutter
version: 1.0.0
homepage: https://github.com/nikeorever/dartrofit/tree/master/dartrofit

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  http: ^0.12.2
  quiver: ^2.1.3
  wedzera: ^0.1.0
  built_collection: ^4.3.2
  built_value: ^7.1.0
  analyzer: ^0.39.14
  http_parser: ^3.1.4
  async: ^2.4.2

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.3
  built_value_generator: ^7.1.0
  build_runner: ^1.10.1
  build_verify: ^1.1.1